### ISSUE TITLE
hc test `WARNING! The git-hash of the runtime and the zome don't match.` - Using older git versions

### ISSUE THREAD

**Issue by btakita** [holochain/holochain-rust#2028]
I'm attempting to run `hc test` & am getting the following error on the call to `await player.spawn()`.

I get the error:
```
WARNING! The git-hash of the runtime and the zome don't match.
Runtime hash: OLD_SHA_1
Zome hash: OLD_SHA_2
```

Where both OLD_SHA_1 & OLD_SHA_2 are SHAs from older commits. Are there some files in an old state that need to be cleaned up? I'll follow up as I find out more information or any suggestions would be appreciated.

**Comment by btakita** [comment]
It turns out that the `Zome hash:` value is correctly pointing to `git rev-parse HEAD`. However the `Runtime hash:` is pointing to a SHA that is not in the git repo.

**Comment by btakita** [comment]
It looks like this was on an older version, so this issue may no longer be relevant.

Here's the `Cargo.toml`.

```toml
[package]
name = "cogov"
version = "0.1.0"
authors = ["hc-scaffold-framework"]
edition = "2018"

[dependencies]
serde = "=1.0.89"
serde_json = { version = "=1.0.39", features = ["preserve_order"] }
serde_derive = "=1.0.89"
hdk = "=0.0.38-alpha14"
hdk_proc_macros = "=0.0.38-alpha14"
holochain_wasm_utils = "=0.0.38-alpha14"
holochain_json_derive = "=0.0.1-alpha2"
log = "0.4"
time = "0.1"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
```

I have since upgraded the hdk & created a forum request with an issue that I'm running across.

https://forum.holochain.org/t/hc-test-from-hdk-0-0-42-alpha1-futures-io-error-e0106-missing-lifetime-specifier/1602
