### ISSUE TITLE
state of nix in travis

### ISSUE THREAD

**Issue by thedavidmeister** [holochain/holochain-rust#633]
## overview

sister of state of nix-shell on mac os X #632
sister of state of nix in windows #634
sister of state of nix in ubuntu #635
child of shell.nix instead of makefile for nixos #627

## R&D

i know very little atm

- _apparently_ travis has native nix support https://docs.travis-ci.com/user/languages/nix/
- nixos wiki has more info about caching and sandboxing https://nixos.wiki/wiki/Nix_on_Travis
- of course, travis caches are fragile, so that will be something to watch out for https://github.com/travis-ci/travis-ci/issues/6604 - we could expect ~3-6 min runs for a well tuned/cached nix based travis run

**Comment by nomeata** [comment]
Works nicely on Linux for me, but not on OSX: https://travis-ci.community/t/cannot-use-nix-support-on-osx/2927

**Comment by thedavidmeister** [comment]
ah! actually we got this working in an alpine docker over on circle ci

we can close this out :)

**Comment by thedavidmeister** [comment]
@nomeata here's an example of nix on mac on ci https://circleci.com/gh/holochain/holochain-rust/16197

**Comment by nomeata** [comment]
I am still using Travis, but this worked for me, avoiding `language: nix`:
```
    - env: TARGET=osx-exe
      os: osx
      language: generic
      before_install:
      - curl https://nixos.org/nix/install | sh
      - source /Users/travis/.nix-profile/etc/profile.d/nix.sh
```
